---
- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details.
- ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow all access to tcp port 22
  ufw:
    rule: allow
    port: 22
    proto: tcp
